name: flask_web_dev
channels:
- conda-forge
- default
dependencies:
- python=3.6.2
- flask=0.12.2
- flask-login=0.4.0
- flask-mail=0.9.1
- flask-migrate=2.1.1
- flask-moment=0.5.1
- flask-script=2.0.6
- flask-sqlalchemy=2.3.0
- flask-wtf=0.14.2
- werkzeug=0.12.2
- pip:
  - flask-bootstrap=3.3.7.1
